# Artificial Neural Network

### Importing the libraries

In [63]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [64]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [65]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [66]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [67]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

## Part 2 - Building the ANN

### Initializing the ANN

In [69]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [70]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [71]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [72]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [91]:
ann.compile(optimizer= 'adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [92]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 26.6999
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6119
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 27.1268
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7819
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7577
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8495
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8121
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 27.2134
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7302
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7177
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7663
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 27.1885
E

### Predicting the results of the Test set

In [93]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[453.4  458.96]
 [462.47 463.29]
 [437.92 435.27]
 ...
 [477.37 476.22]
 [423.7  440.29]
 [464.73 467.92]]
